### ISSUE TITLE
DNS seems not to update via cron

### ISSUE THREAD

**Issue by tackin** [freifunktrier/ansible#3]
Still ffpi.fftr is not resolved. Guess DNS-Update via cron is still not working.

**Comment by Ranlvor** [comment]
Can halfly confirm: draco, the host not managed by ansible, does not resolve ffpi.fftr. The ansible-hosts (ankerstich, baldur, salem) are not affected.

**Comment by Ranlvor** [comment]
```
;; ANSWER SECTION:
ffpi.fftr.              7200    IN      A       10.172.5.1
```

Did rollout the job manually on draco and confirmed via dig @127.0.0.1.
